# System settings
host: 0.0.0.0

# Site settings
title: Antonello Pellecchia
description: > # this means to ignore newlines until "baseurl:"
  Small, personal blog on mathematics, physics and programming,
  with some digressions in music and literature.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://antonellopellecchia.github.io" # the base hostname & protocol for your site
disqus_enabled: True
disqus_username: caverndman
github_username: antonellopellecchia
social_buttons: True
social_twitter: True
social_facebook: True
social_googleplus: True
excerpt_separator: <!--break-->
paginate: 5

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
